# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

skip_docs

default_platform(:android)

platform :android do
  desc 'adding tag and upload to Play Store'
  lane :play_store do |options|
    upload_to_play_store(
        track: 'alpha',
        aab: 'app/build/outputs/bundle/release/app-release.aab',
        rollout: '1.0',
    )
  end
end

